Harmonization of shield styles
TruckersMP/API-Client pull request #53
Opened 2023-06-29 15:25 UTC by Ahhj93

**Before:**
![Before](https://github.com/TruckersMP/API-Client/assets/69793084/c046f9fc-7bb0-49b5-9c3e-5e93c9c78f75)

**After:**
![After](https://github.com/TruckersMP/API-Client/assets/69793084/bd3b0e3a-6d91-4d01-a035-c134ae1f134f)

2023-06-29 15:58 UTC, 3ventic approved these changes

2023-06-29 16:00 UTC, 3ventic requested changes

2023-06-29 16:00 UTC, 3ventic commented on README.md
> +<a href="https://github.styleci.io/repos/57324164"><img src="https://github.styleci.io/repos/57324164/shield?style=flat&branch=6.x&branch=master" alt="StyleCI Status"></a>
extra branch param shouldn't be there

2023-06-29 16:41 UTC, Ahhj93 commented on README.md
> +<a href="https://github.styleci.io/repos/57324164"><img src="https://github.styleci.io/repos/57324164/shield?style=flat&branch=6.x&branch=master" alt="StyleCI Status"></a>
> extra branch param shouldn't be there

It's ok

2023-06-29 16:49 UTC, 3ventic approved these changes

2023-06-30 07:37 UTC, bensherred approved these changes

2023-06-30 07:37 UTC, merged