Changed role on CompanyRole to nullable
TruckersMP/API-Client pull request #54
Opened 2023-08-02 17:12 UTC by shardick

This PR fixes the CompanyRole when API returns the `order` property at null

2023-08-02 17:18 UTC, ShawnCZek requested changes
May you also please share an example payload where the order is actually `null`? I have just checked the official documentation and it states that the field is required.

2023-08-02 17:18 UTC, ShawnCZek commented on src/Models/CompanyRole.php
> +        $this->order = $this->getValue('order', null);
The second parameter is `null` by default. This implicit value is unnecessary and should be removed.

2023-08-03 17:54 UTC, shardick commented
My VTC (id 24 - https://api.truckersmp.com/v2/vtc/24/roles) were returning null for Owner role yesterday but after reording roles from the site, the null turned to 0.

2023-08-03 22:19 UTC, ShawnCZek commented
I have forwarded this to web developers as this sounds more like an issue with the API, especially if it is fine now, but it was not before. I, or someone else, will get back to you once this has been internally discussed.

2023-08-19 10:50 UTC, ShawnCZek commented
This was a bug that was already fixed four years ago. However, it still affected companies created before that date. Therefore, we ran a query to fix all these leftover null values, and the API should no longer return `null` for the role order.

Thank you for bringing this to our attention. 🎉

2023-08-19 10:50 UTC, closed without merging